### ISSUE TITLE
lingo-db website

### ISSUE THREAD

**Issue by Demon-0511** [lingo-db/lingo-db#6]
it seems that https://www.lingo-db.com/interface/ doesn't work now

**Comment by jungmair** [comment]
Hi, I am currently on vacation, but it seems that all of the chairs servers (where the interface is hosted) are not reachable at the moment (e.g. https://db.in.tum.de). Will be probably fixed soon (Monday?).

Anyway thanks for raising this :)

**Comment by jungmair** [comment]
Is now working again
